### ISSUE TITLE
Make group members searchable

### ISSUE THREAD

**Issue by hagelschaden** [TimothyAnders/FetlifeGetMembers#1]
Thanks for this great script! Do you think it would also be possible to get all the members of a specific group?

**Comment by TimothyAnders** [comment]
Just uploaded a folder `get_users_from_group` to the repo. It contains a script to do this. Same process, but the page looks different so I had to modify the script

**Comment by TimothyAnders** [comment]
Let me know how that works and I'll close this issue if it does!

**Comment by hagelschaden** [comment]
Yes it works!!! Thank you so much!!
